apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-client
  labels:
    app: map-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: map-client
  template:
    metadata:
      labels:
        app: map-client
    spec:
      containers:
        - name: map-client
          image: registry.digitalocean.com/kpi-demo/hiveemulator:map-client
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "250m"

          env:
            - name: VITE_API_BASE_URL
              value: http://129.212.140.202/control/api/v1/client
          # volumeMounts:
          #   - name: config-volume
          #     mountPath: /usr/share/nginx/html/config.json
          #     subPath: config.json
      volumes:
        - name: config-volume
          # configMap:
          #   name: map-client-config
      imagePullSecrets:
        - name: digitalocean-registry-secret
