# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: cicd-service-account
#   namespace: dev

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: cicd-deployer-role
# roleRef:
#   kind: ClusterRole
#   name: cluster-admin
#   apiGroup: rbac.authorization.k8s.io
# subjects:
#   - kind: ServiceAccount
#     name: cicd-service-account
#     namespace: dev  # тот же namespace, что у ServiceAccount